# Generated by Django 3.0 on 2020-07-20 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(help_text='The name of a Section/Category you want to create for articles to be nested under. Useful for grouping related articles together', max_length=40, verbose_name='Category Name')),
            ],
        ),
        migrations.CreateModel(
            name='Commenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commenter_email', models.EmailField(help_text="The email address is only used for computing a username, which is given by eveything before the '@' (ampersand) sign. That makes it more likely that the username will be unique.", max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('body_text', models.TextField()),
                ('publication_date', models.DateField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(default='Etc', on_delete=django.db.models.deletion.CASCADE, to='posts.Category')),
                ('tags', models.ManyToManyField(to='tags.Tags')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(help_text='A comment to be posted under a particular post')),
                ('associated_post', models.ForeignKey(help_text='The respective Post that the comment is associated with. If the post is deleted, the associated comments get deleted as well.', on_delete=django.db.models.deletion.CASCADE, to='posts.Post')),
                ('author', models.ForeignKey(help_text='The author of the comment. The user is prompted for their email address before submitting a comment, with a username being computer out of the address', on_delete=django.db.models.deletion.CASCADE, to='posts.Commenter')),
            ],
        ),
    ]
