# Generated by Django 3.0 on 2020-07-21 10:21

from django.db import migrations
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body_text',
            field=posts.models.NonStrippingTextField(),
        ),
    ]
