# Generated by Django 3.0 on 2020-07-30 11:58

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200721_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commenter',
            name='commenter_email',
            field=models.EmailField(help_text="The email address is only used for computing a username, which is given by eveything before the '@' (ampersand) sign. That makes it more likely that the username will be unique withou having to think of an original username.", max_length=254),
        ),
        migrations.AlterField(
            model_name='comments',
            name='author',
            field=models.ForeignKey(help_text='The author of the comment. The commenter has to fill out an email address field before submitting a comment, with a username being computed from the address by discarding everything after and including the ampersand', on_delete=django.db.models.deletion.CASCADE, to='posts.Commenter'),
        ),
        migrations.AlterField(
            model_name='post',
            name='body_text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
